export const styles = {
  page: {
    backgroundColor: "#0f172a",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    fontFamily: "sans-serif",
    color: "#f1f5f9",
  },
  navbar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1e293b",
    padding: "1rem 2rem",
  },
  logo: {
    color: "#38bdf8",
    fontSize: "1.2rem",
    margin: 0,
  },
  navLinks: {
    display: "flex",
    flexDirection: "row",
    gap: "0.5rem",
    margin: 0,
  },
  navLink: {
    padding: "0.5rem 1rem",
    borderRadius: "6px",
    cursor: "pointer",
    color: "#94a3b8",
    fontSize: "0.95rem",
  },
  container: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "3rem 2rem",
  },
  title: { fontSize: "2rem", fontWeight: "bold", marginBottom: "0.5rem" },
  subtitle: { color: "#94a3b8", fontSize: "0.9rem", marginBottom: "2rem" },
  form: { width: "100%", maxWidth: "660px" },
  row: { display: "flex", gap: "1.5rem", marginBottom: "1.25rem" },
  inputGroup: { flex: 1 },
  label: {
    fontSize: "0.75rem",
    color: "#94a3b8",
    letterSpacing: "0.1em",
    display: "block",
    marginBottom: "0.4rem",
  },
  input: {
    width: "100%",
    padding: "0.65rem 0.75rem",
    borderRadius: "4px",
    border: "1px solid #334155",
    backgroundColor: "#f1f5f9",
    color: "#0f172a",
    fontSize: "0.9rem",
    boxSizing: "border-box",
  },
  passwordWrapper: { position: "relative" },
  eyeIcon: {
    position: "absolute",
    right: "0.75rem",
    top: "50%",
    transform: "translateY(-50%)",
    cursor: "pointer",
    fontSize: "1rem",
  },
  select: {
    width: "100%",
    padding: "0.65rem 0.75rem",
    borderRadius: "4px",
    border: "1px solid #334155",
    backgroundColor: "#1e293b",
    color: "#f1f5f9",
    fontSize: "0.9rem",
    boxSizing: "border-box",
  },
  divider: { borderColor: "#334155", margin: "1.5rem 0" },
  notice: { color: "#94a3b8", fontSize: "0.85rem", marginBottom: "1rem" },
  checkboxRow: { display: "flex", alignItems: "center", marginBottom: "1.5rem" },
  checkboxLabel: { color: "#94a3b8", fontSize: "0.85rem" },
  link: { color: "#f1f5f9", textDecoration: "underline", cursor: "pointer" },
  button: {
    display: "block",
    margin: "0 auto",
    padding: "0.75rem 2.5rem",
    backgroundColor: "#16a34a",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    fontSize: "1rem",
    cursor: "pointer",
  },
  footer: {
    textAlign: "right",
    padding: "1rem 2rem",
    color: "#475569",
    fontSize: "0.8rem",
    borderTop: "1px solid #1e293b",
  },
};
