import { useNavigate } from "react-router-dom";

function Visitor() {
  const navigate = useNavigate();

  return (
    <div style={styles.page}>
      {/* Navbar */}
      <nav style={styles.navbar}>
        <h2 style={styles.logo}>Intrusion Detection</h2>
        <div style={styles.navLinks}>
          <span style={styles.navActive} onClick={() => navigate("/")}>Home</span>
          <span style={styles.navLink} onClick={() => navigate("/about")}>About</span>
          <span style={styles.navLink} onClick={() => navigate("/features")}>Features</span>
          <span style={styles.navLink} onClick={() => navigate("/demo")}>Demo</span>
          <span style={styles.navLink} onClick={() => navigate("/login")}>Login</span>
        </div>
      </nav>

      {/* Hero Section */}
      <div style={styles.hero}>
        <div style={styles.heroLeft}>
          <h1 style={styles.heroTitle}>Visualize & Analyze Network Security Threats</h1>
          <p style={styles.heroSubtitle}>Experience the live analyst dashboard</p>
          <div style={styles.heroButtons}>
            <button style={styles.registerButton} onClick={() => navigate("/register")}>Register</button>
            <button style={styles.signinButton} onClick={() => navigate("/login")}>Sign In</button>
          </div>
        </div>
        <div style={styles.heroRight}>
          <img
            src="/securityimage.jpeg"
            alt="IDS Dashboard Preview"
            style={styles.heroImage}
          />
        </div>
      </div>

      <hr style={styles.divider} />

      {/* About Section */}
      <div style={styles.about}>
        <h3 style={styles.aboutTitle}>About the Project</h3>
        <p style={styles.aboutText}>
          This project aims to build a modern lightweight intrusion detection dashboard
          that makes it easier to analyze logs generated by intrusion detection systems (IDS).
          The system will support multiple IDS tools, including Snort, Suricata, Zeek, and Kismet,
          and display their logs in a single, easy-to-use interface.
        </p>
      </div>

      {/* Footer */}
      <footer style={styles.footer}>
        © 2026 Intrusion Detection Dashboard
      </footer>
    </div>
  );
}

const styles = {
  page: {
    backgroundColor: "#0f172a",
    color: "#f1f5f9",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    fontFamily: "sans-serif",
  },
  navbar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1e293b",
    padding: "1rem 2rem",
  },
  logo: {
    color: "#38bdf8",
    fontSize: "1.2rem",
    margin: 0,
  },
  navLinks: {
    display: "flex",
    flexDirection: "row",
    gap: "0.5rem",
    margin: 0,
  },
  navLink: {
    padding: "0.5rem 1rem",
    borderRadius: "6px",
    cursor: "pointer",
    color: "#94a3b8",
    fontSize: "0.95rem",
  },
  navActive: {
    padding: "0.5rem 1rem",
    borderRadius: "6px",
    cursor: "pointer",
    color: "#f1f5f9",
    fontWeight: "bold",
    fontSize: "0.95rem",
    borderBottom: "2px solid #3b82f6",
    paddingBottom: "2px",
  },
  hero: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "4rem",
    flex: 1,
    gap: "2rem",
  },
  heroLeft: {
    maxWidth: "600px",
  },
  heroTitle: {
    fontSize: "2rem",
    fontWeight: "bold",
    marginBottom: "1rem",
    lineHeight: "1.3",
  },
  heroSubtitle: {
    color: "#94a3b8",
    marginBottom: "2rem",
    fontSize: "0.95rem",
  },
  heroButtons: {
    display: "flex",
    gap: "1rem",
  },
  registerButton: {
    padding: "0.65rem 1.75rem",
    backgroundColor: "#06b6d4",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    fontSize: "1rem",
    cursor: "pointer",
  },
  signinButton: {
    padding: "0.65rem 1.75rem",
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    fontSize: "1rem",
    cursor: "pointer",
  },
  heroRight: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  heroImage: {
    width: "100%",
    maxWidth: "600px",
    minWidth: "150px",
    borderRadius: "12px",
    objectFit: "cover",
  },
  divider: {
    borderColor: "#334155",
    margin: "0 4rem",
  },
  about: {
    padding: "2rem 4rem",
  },
  aboutTitle: {
    fontSize: "1.1rem",
    marginBottom: "0.75rem",
    color: "#f1f5f9",
  },
  aboutText: {
    color: "#94a3b8",
    lineHeight: "1.7",
    fontSize: "0.95rem",
  },
  footer: {
    textAlign: "right",
    padding: "1rem 2rem",
    color: "#475569",
    fontSize: "0.8rem",
    borderTop: "1px solid #1e293b",
  },
};

export default Visitor;
