export const styles = {
  content: {
    flex: 1,
    padding: "2rem",
    background: "#0f172a",
    color: "#f1f5f9",
    fontFamily: "'Inter', sans-serif",
    height: "100vh",
    overflowY: "auto",
    position: "relative",
  },
  toast: (type) => ({
    position: "fixed",
    top: "1.5rem",
    right: "1.5rem",
    zIndex: 9999,
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.75rem 1.25rem",
    borderRadius: "10px",
    fontSize: "0.9rem",
    fontWeight: 500,
    backgroundColor:
      type === "success" ? "#10b981" :
      type === "error" ? "#ef4444" :
      "#3b82f6",
    color: "#fff",
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
  }),
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.65)",
    backdropFilter: "blur(4px)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    backgroundColor: "#1e293b",
    borderRadius: "16px",
    width: "100%",
    maxWidth: "440px",
    border: "1px solid #334155",
    boxShadow: "0 25px 60px rgba(0,0,0,0.5)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1.5rem",
    borderBottom: "1px solid #334155",
  },
  modalTitle: { margin: 0, fontSize: "1.1rem", fontWeight: 700, color: "#f1f5f9" },
  closeBtn: {
    background: "none",
    border: "none",
    color: "#64748b",
    fontSize: "1.4rem",
    cursor: "pointer",
    lineHeight: 1,
    padding: "0 0.25rem",
  },
  modalBody: { padding: "1.5rem" },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "0.75rem",
    padding: "1.25rem 1.5rem",
    borderTop: "1px solid #334155",
  },
  formGroup: { marginBottom: "1.25rem", display: "flex", flexDirection: "column", gap: "0.4rem" },
  fieldLabel: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#60a5fa",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  modalInput: {
    width: "100%",
    padding: "0.75rem 1rem",
    backgroundColor: "#0f172a",
    borderRadius: "8px",
    color: "#f1f5f9",
    fontSize: "0.95rem",
    boxSizing: "border-box",
    outline: "none",
  },
  errorText: { fontSize: "0.8rem", color: "#f87171" },
  infoBox: {
    padding: "0.75rem 1rem",
    backgroundColor: "rgba(59,130,246,0.1)",
    border: "1px solid rgba(59,130,246,0.3)",
    borderRadius: "8px",
    fontSize: "0.85rem",
    color: "#93c5fd",
    lineHeight: 1.5,
  },
  modalSaveBtn: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "#10b981",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  modalCancelBtn: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "transparent",
    color: "#94a3b8",
    border: "1px solid #334155",
    borderRadius: "8px",
    fontSize: "0.9rem",
    cursor: "pointer",
  },
  header: { marginBottom: "2rem" },
  pageTitle: { fontSize: "2rem", fontWeight: "800", margin: 0 },
  subtitle: { color: "#94a3b8", fontSize: "1rem", margin: "0.5rem 0 0 0" },
  profileCard: {
    background: "#1e293b",
    borderRadius: "20px",
    padding: "2rem",
    border: "1px solid #334155",
    marginBottom: "1.5rem",
  },
  avatarRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
    paddingBottom: "1rem",
    borderBottom: "1px solid #334155",
  },
  leftSection: { display: "flex", alignItems: "center", gap: "1rem" },
  avatarSection: { position: "relative" },
  avatar: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    background: "#3b82f6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.375rem",
    fontWeight: "700",
    color: "white",
  },
  statusDot: {
    position: "absolute",
    bottom: "-2px",
    right: "-2px",
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    background: "#10b981",
    border: "3px solid #1e293b",
  },
  profileName: { fontSize: "1.3rem", fontWeight: "800", margin: "0 0 0.2rem 0" },
  profileEmail: { fontSize: "0.85rem", color: "#64748b", margin: 0 },
  badgeRow: { display: "flex", gap: "0.5rem" },
  roleBadgeSmall: {
    padding: "0.25rem 0.6rem",
    background: "#3b82f6",
    color: "white",
    borderRadius: "6px",
    fontSize: "0.7rem",
    fontWeight: 600,
  },
  statusBadgeSmall: {
    padding: "0.25rem 0.6rem",
    background: "#10b981",
    color: "white",
    borderRadius: "6px",
    fontSize: "0.7rem",
    fontWeight: 600,
  },
  inputGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1.25rem",
    marginBottom: "2rem",
  },
  fieldGroup: { display: "flex", flexDirection: "column", gap: "0.375rem" },
  label: {
    fontSize: "0.6875rem",
    fontWeight: "700",
    color: "#60a5fa",
    textTransform: "uppercase",
  },
  input: (editing) => ({
    padding: "0.875rem 1rem",
    background: editing ? "#2d3748" : "#1a202c",
    border: editing ? "2px solid #3b82f6" : "1px solid #4a5568",
    borderRadius: "10px",
    color: "#f1f5f9",
    fontSize: "0.9375rem",
    cursor: editing ? "text" : "default",
    pointerEvents: editing ? "auto" : "none",
    outline: "none",
    transition: "border 0.2s, background 0.2s",
  }),
  actionSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "1rem",
  },
  editActions: {
    display: "flex",
    gap: "1rem",
  },
  btn: {
    padding: "0.75rem 1.75rem",
    border: "none",
    borderRadius: "10px",
    fontWeight: "600",
    cursor: "pointer",
    fontSize: "0.875rem",
  },
  passwordBtn: {
    background: "transparent",
    color: "#94a3b8",
    border: "1px solid #4a5568",
  },
  editBtn: { background: "#3b82f6", color: "white" },
  saveBtn: { background: "#10b981", color: "white" },
  cancelBtn: { background: "transparent", color: "#94a3b8", border: "1px solid #4a5568" },
};