export const styles = {
  pageContainer: {
    flex: 1,
    padding: "2rem",
    backgroundColor: "#0f172a",
    color: "#f1f5f9",
    overflowY: "auto",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    position: "relative",
  },
  toast: (type) => ({
    position: "fixed",
    top: "1.5rem",
    right: "1.5rem",
    zIndex: 9999,
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    padding: "0.75rem 1.25rem",
    borderRadius: "10px",
    fontSize: "0.9rem",
    fontWeight: 500,
    backgroundColor: type === 'success' ? "#10b981" : "#ef4444",
    color: "#fff",
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
  }),
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.65)",
    backdropFilter: "blur(4px)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalBox: {
    backgroundColor: "#1e293b",
    borderRadius: "16px",
    padding: "2rem",
    width: "100%",
    maxWidth: "480px",
    border: "1px solid #334155",
    boxShadow: "0 25px 60px rgba(0,0,0,0.5)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "1.25rem",
  },
  modalSubtitle: {
    margin: "0 0 0.2rem 0",
    fontSize: "0.75rem",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontWeight: 600,
  },
  modalTitle: {
    margin: 0,
    fontSize: "1.4rem",
    fontWeight: 700,
    color: "#f1f5f9",
  },
  modalClose: {
    background: "none",
    border: "none",
    color: "#64748b",
    fontSize: "1.1rem",
    cursor: "pointer",
    padding: "0.25rem 0.5rem",
    borderRadius: "6px",
    lineHeight: 1,
  },
  modalStatusRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "1.5rem",
    paddingBottom: "1.25rem",
    borderBottom: "1px solid #334155",
  },
  modalTimestamp: {
    fontSize: "0.8rem",
    color: "#64748b",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1rem",
    marginBottom: "1.75rem",
  },
  detailItem: {
    display: "flex",
    flexDirection: "column",
    gap: "0.3rem",
  },
  detailLabel: {
    fontSize: "0.75rem",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    fontWeight: 600,
  },
  detailValue: {
    fontSize: "0.95rem",
    color: "#f1f5f9",
    fontWeight: 500,
  },
  editInput: {
    padding: "0.6rem 0.8rem",
    backgroundColor: "#0f172a",
    border: "1px solid #475569",
    borderRadius: "8px",
    color: "#f1f5f9",
    fontSize: "0.9rem",
  },
  modalActions: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
  },
  btnEdit: {
    flex: 1,
    padding: "0.75rem",
    backgroundColor: "#334155",
    color: "#f1f5f9",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnToggle: (status) => ({
    flex: 1,
    padding: "0.75rem",
    backgroundColor: status === 'Active' ? "#1e3a5f" : "#14532d",
    color: status === 'Active' ? "#60a5fa" : "#4ade80",
    border: `1px solid ${status === 'Active' ? '#3b82f6' : '#22c55e'}`,
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  }),
  btnDelete: {
    padding: "0.75rem 1rem",
    backgroundColor: "transparent",
    color: "#f87171",
    border: "1px solid #7f1d1d",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnSave: {
    flex: 1,
    padding: "0.75rem",
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnSecondary: {
    flex: 1,
    padding: "0.75rem",
    backgroundColor: "#334155",
    color: "#f1f5f9",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  header: { marginBottom: "2rem" },
  pageTitle: {
    fontSize: "2rem",
    fontWeight: 700,
    margin: "0 0 0.5rem 0",
    color: "#f1f5f9",
  },
  tableSection: {
    backgroundColor: "#1e293b",
    padding: "1.5rem",
    borderRadius: "12px",
    marginBottom: "2rem",
  },
  tableHeader: { marginBottom: "1.5rem" },
  searchInput: {
    width: "100%",
    padding: "0.875rem 1rem",
    backgroundColor: "#334155",
    border: "1px solid #475569",
    borderRadius: "8px",
    color: "#f1f5f9",
    fontSize: "0.95rem",
    boxSizing: "border-box",
  },
  logsTable: { width: "100%", borderCollapse: "collapse" },
  th: {
    padding: "1rem",
    textAlign: "left",
    color: "#94a3b8",
    fontSize: "0.85rem",
    fontWeight: 600,
    textTransform: "uppercase",
    borderBottom: "1px solid #334155",
  },
  tr: { borderBottom: "1px solid #334155" },
  
  trHover: {
    backgroundColor: "#253549",
    borderBottom: "1px solid #334155",
  },
  td: { padding: "1rem", fontSize: "0.9rem", color: "#f1f5f9" },
  statusBadge: (status) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    padding: "0.25rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.8rem",
    fontWeight: 600,
    backgroundColor: status === 'active' ? "rgba(16,185,129,0.15)" : "rgba(239,68,68,0.15)",
    color: status === 'active' ? "#10b981" : "#ef4444",
    border: `1px solid ${status === 'active' ? 'rgba(16,185,129,0.3)' : 'rgba(239,68,68,0.3)'}`,
  }),
  statusDot: (status) => ({
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: status === 'active' ? "#10b981" : "#ef4444",
    display: "inline-block",
  }),
  actionBtn: {
    padding: "0.4rem 0.85rem",
    backgroundColor: "#334155",
    color: "#94a3b8",
    border: "1px solid #475569",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "1.1rem",
    fontWeight: 700,
    letterSpacing: "0.05em",
  },
  formSection: {
    backgroundColor: "#1e293b",
    padding: "1.5rem",
    borderRadius: "12px",
  },
  formTitle: {
    margin: "0 0 1.25rem 0",
    fontSize: "1rem",
    fontWeight: 600,
    color: "#94a3b8",
  },
  form: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "1rem",
  },
  input: {
    padding: "0.875rem 1rem",
    backgroundColor: "#334155",
    border: "1px solid #475569",
    borderRadius: "8px",
    color: "#f1f5f9",
    fontSize: "0.95rem",
  },
  fileInputContainer: {
    position: "relative",
    gridColumn: "1 / -1",
  },
  fileInputHidden: { display: "none" },
  fileInputLabel: (file) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    padding: "0.875rem 1rem",
    backgroundColor: file ? "rgba(16,185,129,0.1)" : "#1e293b",
    border: file ? "2px solid #059669" : "2px dashed #475569",
    borderRadius: "8px",
    color: file ? "#10b981" : "#94a3b8",
    fontSize: "0.95rem",
    fontWeight: file ? 500 : 400,
    cursor: "pointer",
    minHeight: "56px",
    textAlign: "center",
  }),
  submitBtn: {
    padding: "0.875rem 1.5rem",
    backgroundColor: "#10b981",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.95rem",
    fontWeight: 600,
    cursor: "pointer",
    gridColumn: "1 / -1",
  },
};
