
export const styles = {
  content: {
    flex: 1,
    padding: "2rem",
    overflowY: "auto",
    backgroundColor: "#0f172a",
    color: "#f1f5f9",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    position: "relative",
  },
  header: { marginBottom: "2rem" },
  pageTitle: { fontSize: "2rem", fontWeight: 700, margin: "0 0 0.5rem 0", color: "#f1f5f9" },
  subtitle: { color: "#94a3b8", fontSize: "1rem", margin: 0 },
  controls: { display: "flex", gap: "1rem", alignItems: "center", marginBottom: "1rem" },
  searchInput: {
    flex: 1,
    padding: "0.875rem 1rem",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "8px",
    color: "#f1f5f9",
    fontSize: "0.95rem",
  },
  addUserBtn: {
    padding: "0.875rem 1.5rem",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.95rem",
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },

  // ── Filter bar ────────────────────────────────────────────
  filterBar: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    flexWrap: "wrap",
    marginBottom: "0.75rem",
    padding: "0.875rem 1.25rem",
    backgroundColor: "#1e293b",
    borderRadius: "10px",
    border: "1px solid #334155",
  },
  filterGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
  },
  filterLabel: {
    fontSize: "0.78rem",
    fontWeight: 600,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    whiteSpace: "nowrap",
  },
  selectDropdown: {
    padding: "0.45rem 0.75rem",
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#f1f5f9",
    fontSize: "0.85rem",
    cursor: "pointer",
    outline: "none",
  },
  clearBtn: {
    marginLeft: "auto",
    padding: "0.45rem 0.9rem",
    backgroundColor: "transparent",
    border: "1px solid #475569",
    borderRadius: "6px",
    color: "#94a3b8",
    fontSize: "0.82rem",
    cursor: "pointer",
    whiteSpace: "nowrap",
    fontFamily: "inherit",
  },
  resultsCount: {
    fontSize: "0.82rem",
    color: "#64748b",
    margin: "0 0 1rem 0",
  },

  tableSection: { backgroundColor: "#1e293b", padding: "1.5rem", borderRadius: "12px" },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    padding: "1rem",
    textAlign: "left",
    color: "#94a3b8",
    fontSize: "0.85rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    borderBottom: "1px solid #334155",
  },
  tr: { borderBottom: "1px solid #334155" },
  trHover: { backgroundColor: "#253549", borderBottom: "1px solid #334155" },
  td: { padding: "1rem", fontSize: "0.9rem", color: "#f1f5f9" },
  emptyTd: { padding: "3rem", textAlign: "center", color: "#94a3b8", fontStyle: "italic" },
  userInfo: { display: "flex", alignItems: "center", gap: "0.75rem" },
  avatar: (id) => ({
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: `hsl(${(id * 137) % 360}, 50%, 45%)`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "white",
    flexShrink: 0,
  }),
  roleBadge: (role) => ({
    padding: "0.25rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.8rem",
    fontWeight: 600,
    backgroundColor: role === "Admin" ? "#3b82f6" : "#10b981",
    color: "#fff",
  }),
  statusBadge: (status) => ({
    padding: "0.25rem 0.75rem",
    borderRadius: "9999px",
    fontSize: "0.8rem",
    fontWeight: 600,
    backgroundColor:
      status === "Active" ? "rgba(16,185,129,0.15)" :
      status === "Pending" ? "rgba(245,158,11,0.15)" :
      "rgba(239,68,68,0.15)",
    color:
      status === "Active" ? "#10b981" :
      status === "Pending" ? "#f59e0b" :
      "#ef4444",
    border: `1px solid ${
      status === "Active" ? "rgba(16,185,129,0.3)" :
      status === "Pending" ? "rgba(245,158,11,0.3)" :
      "rgba(239,68,68,0.3)"
    }`,
  }),
  menuTrigger: {
    padding: "0.4rem 0.85rem",
    backgroundColor: "#334155",
    color: "#94a3b8",
    border: "1px solid #475569",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "1.1rem",
    fontWeight: 700,
    letterSpacing: "0.05em",
  },
  dropdown: {
    position: "absolute",
    right: 0,
    top: "calc(100% + 6px)",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "10px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.5)",
    zIndex: 100,
    minWidth: "160px",
    overflow: "hidden",
  },
  dropdownItem: {
    display: "block",
    width: "100%",
    padding: "0.65rem 1rem",
    background: "none",
    border: "none",
    borderBottom: "1px solid #334155",
    textAlign: "left",
    fontSize: "0.88rem",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#f1f5f9",
  },
  toast: (type) => ({
    position: "fixed",
    top: "1.5rem",
    right: "1.5rem",
    zIndex: 9999,
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    padding: "0.75rem 1.25rem",
    borderRadius: "10px",
    fontSize: "0.9rem",
    fontWeight: 500,
    backgroundColor: type === "success" ? "#10b981" : "#ef4444",
    color: "#fff",
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
  }),
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#1e293b",
    borderRadius: "12px",
    width: "90%",
    maxWidth: "480px",
    border: "1px solid #334155",
    boxShadow: "0 25px 50px rgba(0,0,0,0.5)",
  },
  modalHeader: {
    padding: "1.5rem",
    borderBottom: "1px solid #334155",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: { margin: 0, fontSize: "1.1rem", fontWeight: 700, color: "#f1f5f9" },
  modalBody: { padding: "1.5rem" },
  modalFooter: {
    padding: "1.25rem 1.5rem",
    borderTop: "1px solid #334155",
    display: "flex",
    gap: "0.75rem",
    justifyContent: "flex-end",
  },
  formGroup: { marginBottom: "1.25rem", display: "flex", flexDirection: "column", gap: "0.4rem" },
  fieldLabel: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#60a5fa",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  input: {
    width: "100%",
    padding: "0.75rem 1rem",
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "8px",
    color: "#f1f5f9",
    fontSize: "0.95rem",
    boxSizing: "border-box",
  },
  errorText: { fontSize: "0.8rem", color: "#f87171" },
  infoBox: {
    padding: "0.875rem 1rem",
    backgroundColor: "rgba(59,130,246,0.1)",
    border: "1px solid rgba(59,130,246,0.3)",
    borderRadius: "8px",
    fontSize: "0.85rem",
    color: "#93c5fd",
    lineHeight: 1.5,
  },
  resetEmailBox: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "0.875rem 1rem",
    backgroundColor: "#0f172a",
    borderRadius: "8px",
    border: "1px solid #334155",
    fontSize: "0.95rem",
  },
  saveBtn: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "#10b981",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  cancelBtn: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "transparent",
    color: "#94a3b8",
    border: "1px solid #334155",
    borderRadius: "8px",
    fontSize: "0.9rem",
    cursor: "pointer",
  },
  closeBtn: {
    background: "none",
    border: "none",
    fontSize: "1.5rem",
    color: "#94a3b8",
    cursor: "pointer",
    lineHeight: 1,
    padding: "0 0.25rem",
  },
};
